### PR TITLE
Create the attraction page and do the slideshow effect. First: In fro…

### PR DESCRIPTION
**Pull request by cvbn55688**
…nt page, user can choice the attraction. When click the attraction, it will redirect to the attraction page by JS. Second: In the attraction page, user can click the arrow to change the photo. BTW the photo will take turn by itself every three seconds. In the attraction page, user can click the 'small dots', witch is under the photo, to change the showing photo.

### CODE REVIEW

**Comment by cvbn55688** [comment]
testing URLs:
http://54.168.68.62:3000/
http://54.168.68.62:3000/attraction/3

**Review by cwpeng — APPROVED** [review]
Good. Done.

**Comment by cwpeng** [comment]
You can try to use Flask Blueprint to seperate API routes from app.py

**Comment by cvbn55688** [comment]
OK, I will try to use Blueprint. Thanks!!

**Pull request merged**
