### PR TITLE
Develop a website

### PR DESCRIPTION
**Pull request by cvbn55688**
何致翰 Pull Request

### CODE REVIEW

**Comment by cwpeng** [comment]
Paste your live URLs for testing.

**Comment by cvbn55688** [comment]
Sorry!! I'm trying to fix some bug and finally done.
There is the URLs for testing:
http://54.168.68.62:3000/api/attractions?page=0
http://54.168.68.62:3000/api/attractions?page=0&keyword=北
http://54.168.68.62:3000/api/attractions?page=0&keyword=宗教信仰
http://54.168.68.62:3000/api/categories
http://54.168.68.62:3000/api/attraction/16

**Review by cwpeng — CHANGES_REQUESTED** [review]
Result is OK.

But it's much better to use `LIMIT` to do pagination than do it in your own code.

Fix this issue and re-request review.

**Comment by cvbn55688** [comment]
Ok it's done, I fixed the issue and update the server's script.

**Comment by cwpeng** [comment]
Re-request review from reviewers section in the right side of this page, so that I can review for you.

**Comment by cvbn55688** [comment]
ok, I already re-request review from reviewers.

**Review by cwpeng — APPROVED** [review]
Good. You are Second One. :)

**Comment by cvbn55688** [comment]
Thanks!!!

**Pull request merged**
